name: BeginnerLifeTutorial
version: '1.0'
main: beginnerlifetutorial.beginnerlifetutorial.BeginnerLifeTutorial
api-version: 1.15
authors: [ 46kuri_, temps1101 ]

commands:
  tutorialAdmin:
    permission: tutorial.permission.admin
  tutorial:
    permission: tutorial.permission.member
  stepTutorial:
    permission: tutorial.permission.member

permissions:
  tutorial.permission.admin:
    default: op
  tutorial.permission.member:
    default: true