package beginnerlifetutorial.beginnerlifetutorial.enums;

public enum TutorialPhase {
    // メッセージ系
    NEXT_MESSAGE_PRESSED_1, NEXT_MESSAGE_PRESSED_2, NEXT_MESSAGE_PRESSED_3, NEXT_MESSAGE_PRESSED_4, NEXT_MESSAGE_PRESSED_5, NEXT_MESSAGE_PRESSED_6, NEXT_MESSAGE_PRESSED_7, NEXT_MESSAGE_PRESSED_8, NEXT_MESSAGE_PRESSED_9, NEXT_MESSAGE_PRESSED_10, NEXT_MESSAGE_PRESSED_11, NEXT_MESSAGE_PRESSED_12, NEXT_MESSAGE_PRESSED_13, NEXT_MESSAGE_PRESSED_14,

    // スタート
    START,

    // 資源チュートリアル
    HOE_BUTTON_PRESSED, WAITING_WHEAT_HARVESTED, WHEAT_HARVESTED, START_SKILL, WAITING_GREEN_TERRA_FINISHED, GREEN_TERRA_FINISHED, TP_CAVE, OTT_GAVE, PICKAXE_BOUGHT
}
