package beginnerlifetutorial.beginnerlifetutorial.enums;

public enum TutorialPhase {
    // メッセージ系
    NEXT_MESSAGE_PRESSED_1, NEXT_MESSAGE_PRESSED_2, NEXT_MESSAGE_PRESSED_3, NEXT_MESSAGE_PRESSED_4, NEXT_MESSAGE_PRESSED_5, NEXT_MESSAGE_PRESSED_6, NEXT_MESSAGE_PRESSED_7,

    // スタート
    START,

    // 資源チュートリアル
    WAITING_WHEAT_HARVESTED, WHEAT_HARVESTED, WAITING_GREEN_TERRA_FINISHED, GREEN_TERRA_FINISHED,
    HOE_BUTTON_PRESSED, START_SKILL
}
