# TSPは三重塔のことです。

firstSpawnLocation: [0, 0, 0]
tspLocation: [-8, 8, -522]

# チュートリアルへの扉の座標系
resourceDoor: [0, 0, 0]
shopMoneyDoor: [0, 0, 0]
dungeonDoor: [0, 0, 0]
raidDoor: [0, 0, 0]

# 資源チュートリアルの設定
resourceLocation: [0, 0, 0]
shopMoneyLocation: [0, 0, 0]
dungeonLocation: [0, 0, 0]
raidLocation: [0, 0, 0]