# TSPは三重塔のことです。

firstSpawnLocation:
  ==: org.bukkit.Location
  world: tutorial
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0

tspLocation:
  ==: org.bukkit.Location
  world: tutorial
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0

# チュートリアルへの扉の座標系
resourceDoorLocation:
  ==: org.bukkit.Location
  world: tutorial
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0

shopMoneyDoorLocation:
  ==: org.bukkit.Location
  world: tutorial
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0

dungeonDoorLocation:
  ==: org.bukkit.Location
  world: tutorial
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0

raidDoorLocation:
  ==: org.bukkit.Location
  world: tutorial
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0

# 資源チュートリアルの設定
resourceLocation:
  ==: org.bukkit.Location
  world: tutorial
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0

resourceCaveLocation:
  ==: org.bukkit.Location
  world: tutorial
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0

shopMoneyLocation:
  ==: org.bukkit.Location
  world: tutorial
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0

dungeonLocation:
  ==: org.bukkit.Location
  world: tutorial
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0

raidLocation:
  ==: org.bukkit.Location
  world: tutorial
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0
