# TSPは三重塔のことです。

firstSpawnLocation:
  world: 'tutorial'
    x: 0
    y: 0
    z: 0
tspLocation:
  world: 'tutorial'
    x: 0
    y: 0
    z: 0

# チュートリアルへの扉の座標系
resourceDoor:
  world: 'tutorial'
  x: 0
  y: 0
  z: 0
shopMoneyDoor:
  world: 'tutorial'
    x: 0
    y: 0
    z: 0
dungeonDoor:
  world: 'tutorial'
    x: 0
    y: 0
    z: 0
raidDoor:
  world: 'tutorial'
    x: 0
    y: 0
    z: 0

# 資源チュートリアルの設定
resourceLocation:
  world: 'tutorial'
    x: 0
    y: 0
    z: 0
shopMoneyLocation:
  world: 'tutorial'
    x: 0
    y: 0
    z: 0
dungeonLocation:
  world: 'tutorial'
    x: 0
    y: 0
    z: 0
raidLocation:
  world: 'tutorial'
    x: 0
    y: 0
    z: 0