name: BeginnerLifeTutorial
version: '${project.version}'
main: beginnerlifetutorial.beginnerlifetutorial.BeginnerLifeTutorial
api-version: 1.15
authors: [ 46kuri_, temps1101 ]

commands:
  ltutorial:
    description: チュートリアルコマンド
    permission: ltutorial.permission.member

permissions:
  ltutorial.permission.admin:
    default: op
  ltutorial.permission.member:
    default: true