name: BeginnerLifeTutorial
version: '${project.version}'
main: beginnerlifetutorial.beginnerlifetutorial.BeginnerLifeTutorial
api-version: 1.15
authors: [ 46kuri_, temps1101 ]

permissions:
  ltutorial.permission.admin:
    default: op
  ltutorial.permission.member:
    default: true